name: "AWS SSM Send-Command"
author: "Donghyun Peter Kim <peterkimzz69@gmail.com>"

branding:
  icon: "arrow-up-right"
  color: "orange"

description: "Remote EC2 bash command execution."

inputs:
  aws-access-key-id:
    required: true
    description: "AWS access key id"
  aws-secret-access-key:
    required: true
    description: "AWS secret access key"
  aws-region:
    required: true
    description: "Where EC2 instance is"
  instance-ids:
    required: true
    description: "AWS EC2 Instance id or ids"
  branch:
    required: true
    description: "Deploy branch"
  sha:
    required: true
    description: "Deploy sha"
  tag:
    required: true
    description: "Deploy tag"
  comment:
    required: false
    description: "Comment for Send-Command"
    default: "Deployed by Github Actions"

runs:
  using: "node16"
  main: "dist/index.js"
